#!/bin/bash
# Build SuperCaffeinate.app and install it to ~/Applications.
# Hand-assembled bundle, no Xcode project: swiftc plus an Info.plist.
set -euo pipefail

# Resolve through a symlink so the script works when linked elsewhere.
SELF="$0"
while [ -L "$SELF" ]; do SELF="$(readlink "$SELF")"; done
SRC_DIR="$(cd "$(dirname "$SELF")" && pwd)"
APP_NAME="SuperCaffeinate"
EXE=SuperCaffeinate
BUILD="$SRC_DIR/build/$APP_NAME.app"
DEST_DIR="$HOME/Applications"
DEST="$DEST_DIR/$APP_NAME.app"
LABEL=com.sawyer.supercaffeinate-menubar
PLIST="$HOME/Library/LaunchAgents/$LABEL.plist"

rm -rf "$BUILD"
mkdir -p "$BUILD/Contents/MacOS" "$BUILD/Contents/Resources"

/usr/bin/swiftc -O -target "$(uname -m)-apple-macos13" \
  -o "$BUILD/Contents/MacOS/$EXE" \
  "$SRC_DIR/main.swift"

cat > "$BUILD/Contents/Info.plist" <<'PLISTEOF'
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleName</key><string>SuperCaffeinate</string>
  <key>CFBundleDisplayName</key><string>SuperCaffeinate</string>
  <key>CFBundleIdentifier</key><string>com.sawyer.supercaffeinate-menubar</string>
  <key>CFBundleExecutable</key><string>SuperCaffeinate</string>
  <key>CFBundleIconFile</key><string>AppIcon</string>
  <key>CFBundlePackageType</key><string>APPL</string>
  <key>CFBundleShortVersionString</key><string>1.0</string>
  <key>CFBundleVersion</key><string>1</string>
  <key>LSMinimumSystemVersion</key><string>13.0</string>
  <key>LSUIElement</key><true/>
  <key>NSHighResolutionCapable</key><true/>
</dict>
PLISTEOF
echo '</plist>' >> "$BUILD/Contents/Info.plist"

# App icon, generated by icon/make_icon.py and checked in (not rebuilt here).
cp "$SRC_DIR/icon/AppIcon.icns" "$BUILD/Contents/Resources/AppIcon.icns"

# Ad hoc signature so macOS treats it as a stable app identity across rebuilds.
/usr/bin/codesign --force --sign - "$BUILD" >/dev/null 2>&1 || true

# Stop the running copy before replacing it on disk.
if [ -f "$PLIST" ]; then
  launchctl bootout "gui/$(id -u)/$LABEL" 2>/dev/null || true
fi
/usr/bin/pkill -f "/Contents/MacOS/SuperCaffeinate$" 2>/dev/null || true

mkdir -p "$DEST_DIR"
rm -rf "$DEST"
cp -R "$BUILD" "$DEST"

if [ -f "$PLIST" ]; then
  launchctl bootstrap "gui/$(id -u)" "$PLIST"
  echo "Reloaded $LABEL."
else
  open "$DEST"
  echo "Launched $DEST (no LaunchAgent installed yet)."
fi

echo "Installed: $DEST"
